plugins {
    id 'com.android.application'
}

android {
    namespace 'com.battletanks.seeker'
    compileSdk 34

    defaultConfig {
        applicationId "com.battletanks.seeker"
        minSdk 24
        targetSdk 34
        versionCode 3
        versionName "0.3.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    sourceSets {
        main {
            assets.srcDirs = ['src/main/assets']
        }
    }
}

dependencies {
}
