plugins {
    id 'com.android.application'
}

android {
    namespace 'com.battletanks.seeker'
    compileSdk 23

    defaultConfig {
        applicationId "com.battletanks.seeker"
        minSdk 21
        targetSdk 23
        versionCode 1
        versionName "0.1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    sourceSets {
        main {
            assets.srcDirs = ['src/main/assets']
        }
    }
}

dependencies {
}
